// <auto-generated />
using System;
using Kongruencia.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kongruencia.Server.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20200216215838_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Kongruencia.Server.Coverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasColumnType("TEXT");

                    b.Property<int>("BuildNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coverages");
                });

            modelBuilder.Entity("Kongruencia.Server.Coverage", b =>
                {
                    b.OwnsOne("Kongruencia.Server.Metrics", "Metrics", b1 =>
                        {
                            b1.Property<int>("CoverageId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("conditionals")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("coveredconditionals")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("coveredmethods")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("coveredstatements")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("methods")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("statements")
                                .HasColumnType("INTEGER");

                            b1.HasKey("CoverageId");

                            b1.ToTable("Coverages");

                            b1.WithOwner()
                                .HasForeignKey("CoverageId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
